using ArenaBuilder.Core.Platforms.PS3.Pegasus.Mesh;
using ArenaBuilder.Core.Psg;
using ArenaBuilder.Texture.Dds;
using SharpGLTF.Memory;
using SharpGLTF.Schema2;
using System.Collections.Concurrent;

namespace ArenaBuilder.Texture;

/// <summary>
/// Extracts textures from a GLB material, converts PNG/JPG to DDS (DXT5), builds texture PSG files,
/// and returns channel GUIDs so mesh material overrides can link to them.
/// Supports optional BlenRose sidecar JSON material metadata while resolving textures from the GLB.
/// </summary>
public static class GlbTextureAutoBuilder
{
    private sealed record ResolvedTextureSource(
        byte[] EncodedImageBytes,
        bool SourceIsDds,
        string ImageName);

    private static readonly ConcurrentDictionary<string, object> OutputWriteLocks =
        new(StringComparer.OrdinalIgnoreCase);

    /// <summary>Clears accumulated per-path write locks after a large build (safe between builds).</summary>
    public static void ClearOutputWriteLocksCache() => OutputWriteLocks.Clear();

    /// <summary>
    /// Build-scoped memo of the Sobel-normal / linear-specular autogen, keyed by
    /// the diffuse content hash. The per-cell lightmap pipeline produces one
    /// logical source per (diffuse × lightmap-atlas), so the SAME diffuse is
    /// resolved through here dozens–hundreds of times; without this the Sobel
    /// pass re-ran for every atlas source (the "Build DLC hang"). The encode
    /// dedup downstream already collapses the output — this collapses the CPU.
    /// </summary>
    private static readonly ConcurrentDictionary<string, byte[]> AutogenCache = new();

    /// <summary>Clears the autogen memo. Safe between builds.</summary>
    public static void ClearAutogenCache() => AutogenCache.Clear();

    private static string ContentKey(string tag, byte[] bytes)
    {
        using var sha = System.Security.Cryptography.SHA1.Create();
        return tag + ":" + Convert.ToHexString(sha.ComputeHash(bytes));
    }

    public sealed record BuiltTexturePsg(
        string ChannelName,
        string SourceImageName,
        int Width,
        int Height,
        ulong Guid,
        string PsgPath);

    /// <summary>
    /// When materials JSON was used, this is the material_name (e.g. "environment.default") to use as AttributorMaterialName stream in the mesh PSG.
    /// ChannelConfig: when present, used to build only the channels defined in the JSON (textures + scalars).
    /// </summary>
    public sealed record GlbTextureAutoBuildResult(
        ulong? DiffuseGuid,
        ulong? NormalGuid,
        ulong? LightmapGuid,
        ulong? SpecularGuid,
        IReadOnlyList<BuiltTexturePsg> BuiltTextures,
        IReadOnlyList<string> Warnings,
        string? AttributorMaterialStream = null,
        RenderMaterialDataBuilder.BlenroseChannelConfig? ChannelConfig = null)
    {
        public bool HasOverrides =>
            DiffuseGuid.HasValue ||
            NormalGuid.HasValue ||
            LightmapGuid.HasValue ||
            SpecularGuid.HasValue;
    }

    /// <summary>
    /// One channel of a GLB resolved to its pre-encode source bytes plus the encoder flags
    /// <see cref="BuildTextureFromEncodedSource"/> needs. Cheap value object that holds an
    /// already-loaded byte[] and the encode-side decisions (mip count, alpha behavior) so that
    /// emitting the same GLB into N tiles only needs to re-run the encode/PSG-write step,
    /// not the GLB load + channel resolve + autogen step.
    /// </summary>
    public sealed record ResolvedChannelSource(
        string MeshChannelName,
        byte[] EncodedImageBytes,
        bool SourceIsDds,
        string ImageName,
        bool NeedsAlpha,
        bool IsLightmapChannel,
        bool GenerateMipMaps);

    /// <summary>
    /// Result of <see cref="ResolveSourcesFromGlb"/>: the GLB has been loaded, the JSON sidecar
    /// resolved, the diffuse/normal/lightmap/specular channels picked, and any autogenerated
    /// normal/specular maps synthesized from the diffuse. Pass this to <see cref="EmitToTile"/>
    /// once per cPres tile that needs a copy of these textures.
    /// </summary>
    public sealed record ResolvedGlbTextureSources(
        string GlbPath,
        string GlbIdentity,
        string MaterialName,
        ResolvedChannelSource? Diffuse,
        ResolvedChannelSource? Normal,
        ResolvedChannelSource? Lightmap,
        ResolvedChannelSource? Specular,
        bool GeneratedNormal,
        bool GeneratedSpecular,
        string? AttributorMaterialStream,
        RenderMaterialDataBuilder.BlenroseChannelConfig? ChannelConfig,
        IReadOnlyList<string> ResolveWarnings);

    /// <summary>
    /// Auto-builds texture PSGs for one material context in the GLB.
    /// Channel mapping (matches BlenRose node setup):
    /// BaseColor -> diffuse, Normal -> normal, Emissive -> lightmap (BlenRose connects lightmap to Emission),
    /// Occlusion -> lightmap fallback, MetallicRoughness -> specular.
    /// Textures are resolved from the GLB by image_name hint or by standard GLB material channels.
    /// When <paramref name="deduplicationRegistry"/> is provided, identical payloads are deduplicated
    /// (shared GUID, single PSG file); lightmaps dedupe only when payload is identical.
    ///
    /// Internally this is now a thin wrapper around <see cref="ResolveSourcesFromGlb"/> +
    /// <see cref="EmitToTile"/>; tile-build callers should call those directly to share one GLB
    /// load across many cPres tiles.
    /// </summary>
    public static GlbTextureAutoBuildResult BuildFromGlb(
        string glbPath,
        string outputDirectory,
        bool generateMipMaps = true,
        string? materialsJsonPath = null,
        string? materialNameOverride = null,
        string? guidNamespace = null,
        TextureDeduplicationRegistry? deduplicationRegistry = null,
        DerivedTextureGenerator.NormalSynthSettings? normalSynthSettings = null,
        string? deduplicationScope = null,
        CancellationToken cancellationToken = default)
    {
        var sources = ResolveSourcesFromGlb(
            glbPath,
            generateMipMaps,
            materialsJsonPath,
            materialNameOverride,
            guidNamespace,
            normalSynthSettings,
            cancellationToken);

        return EmitToTile(
            sources,
            outputDirectory,
            deduplicationRegistry,
            deduplicationScope,
            cancellationToken);
    }

    /// <summary>
    /// Phase 1 of the texture build: load the GLB, resolve the JSON sidecar, pick the four
    /// channels (diffuse / normal / lightmap / specular), and synthesize autogen normal+specular
    /// from the diffuse when those channels are missing. The expensive raster ops (PNG decode,
    /// Sobel for autogen normal, BCn encode) are NOT done here — only the cheap-ish source
    /// resolution. The returned <see cref="ResolvedGlbTextureSources"/> can be reused for
    /// multiple <see cref="EmitToTile"/> calls so that the GLB is parsed and the autogen runs
    /// only once per build per glbPath, even when the GLB feeds many cPres tiles.
    /// </summary>
    public static ResolvedGlbTextureSources ResolveSourcesFromGlb(
        string glbPath,
        bool generateMipMaps = true,
        string? materialsJsonPath = null,
        string? materialNameOverride = null,
        string? guidNamespace = null,
        DerivedTextureGenerator.NormalSynthSettings? normalSynthSettings = null,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(glbPath))
            throw new ArgumentException("GLB path is required.", nameof(glbPath));
        if (!File.Exists(glbPath))
            throw new FileNotFoundException("GLB file not found.", glbPath);

        var warnings = new List<string>();

        var model = ModelRoot.Load(glbPath);
        string glbStem = Path.GetFileNameWithoutExtension(glbPath);
        string glbIdentity = BuildScopedGlbIdentity(glbPath, glbStem, guidNamespace);

        if (model.LogicalMeshes.Count == 0 || model.LogicalMeshes[0].Primitives.Count == 0)
        {
            warnings.Add("GLB has no meshes/primitives; skipped texture build.");
            return new ResolvedGlbTextureSources(
                glbPath, glbIdentity, materialNameOverride ?? "DefaultMaterial",
                null, null, null, null,
                false, false,
                null, null,
                warnings);
        }

        var prim = model.LogicalMeshes[0].Primitives[0];
        var material = prim.Material ?? model.LogicalMaterials.FirstOrDefault();
        if (material == null)
        {
            warnings.Add("No material found on first primitive; skipped texture build.");
            return new ResolvedGlbTextureSources(
                glbPath, glbIdentity, materialNameOverride ?? "DefaultMaterial",
                null, null, null, null,
                false, false,
                null, null,
                warnings);
        }

        if (!string.IsNullOrWhiteSpace(materialNameOverride))
        {
            var matchedMaterial = model.LogicalMaterials.FirstOrDefault(
                m => string.Equals(m.Name, materialNameOverride, StringComparison.OrdinalIgnoreCase));
            if (matchedMaterial != null)
                material = matchedMaterial;
        }

        string materialName = !string.IsNullOrWhiteSpace(materialNameOverride)
            ? materialNameOverride!
            : (string.IsNullOrWhiteSpace(material.Name) ? "DefaultMaterial" : material.Name);

        var jsonMaterial = TryResolveJsonMaterialConfig(glbPath, materialsJsonPath, materialName, glbStem, warnings);

        // Diffuse.
        cancellationToken.ThrowIfCancellationRequested();
        var diffuseSrc = TryResolveChannelSource(material, jsonMaterial, "diffuse", ["BaseColor"], "diffuse", out string? diffWarn);
        if (diffWarn != null) warnings.Add(diffWarn);
        var diffuseChannel = diffuseSrc != null
            ? new ResolvedChannelSource(
                "diffuse",
                diffuseSrc.EncodedImageBytes,
                diffuseSrc.SourceIsDds,
                diffuseSrc.ImageName,
                NeedsAlpha: ChannelNeedsAlpha("diffuse", jsonMaterial),
                IsLightmapChannel: false,
                GenerateMipMaps: generateMipMaps)
            : null;

        // Normal: prefer GLB/JSON, fall back to autogen-from-diffuse.
        cancellationToken.ThrowIfCancellationRequested();
        var normalSrc = TryResolveChannelSource(material, jsonMaterial, "normal", ["Normal"], "normal", out string? normWarn);
        if (normWarn != null) warnings.Add(normWarn);
        ResolvedChannelSource? normalChannel = null;
        bool generatedNormal = false;
        if (normalSrc != null)
        {
            normalChannel = new ResolvedChannelSource(
                "normal",
                normalSrc.EncodedImageBytes,
                normalSrc.SourceIsDds,
                normalSrc.ImageName,
                NeedsAlpha: ChannelNeedsAlpha("normal", jsonMaterial),
                IsLightmapChannel: false,
                GenerateMipMaps: generateMipMaps);
        }
        else if (diffuseSrc != null)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();
                var synthSettings = normalSynthSettings ?? DerivedTextureGenerator.DefaultNormalSettings;
                byte[] normalPng = DerivedTextureGenerator.GenerateNormalMapPngFromImage(diffuseSrc.EncodedImageBytes, synthSettings);
                string generatedName = BuildGeneratedImageName(diffuseSrc.ImageName, "autogen_normal_sobel_v1");
                normalChannel = new ResolvedChannelSource(
                    "normal",
                    normalPng,
                    SourceIsDds: false,
                    ImageName: generatedName,
                    NeedsAlpha: false,
                    IsLightmapChannel: false,
                    GenerateMipMaps: generateMipMaps);
                generatedNormal = true;
            }
            catch (Exception ex)
            {
                warnings.Add($"Auto-generated normal map skipped: {ex.Message}");
            }
        }

        // Lightmap: forced single-mip (matches retail PS3 lightmap output).
        cancellationToken.ThrowIfCancellationRequested();
        var lightmapSrc = TryResolveChannelSource(material, jsonMaterial, "lightmap", ["Emissive", "Occlusion"], "lightmap", out string? lightWarn);
        if (lightWarn != null) warnings.Add(lightWarn);
        var lightmapChannel = lightmapSrc != null
            ? new ResolvedChannelSource(
                "lightmap",
                lightmapSrc.EncodedImageBytes,
                lightmapSrc.SourceIsDds,
                lightmapSrc.ImageName,
                NeedsAlpha: ChannelNeedsAlpha("lightmap", jsonMaterial),
                IsLightmapChannel: true,
                GenerateMipMaps: false)
            : null;

        // Specular: prefer GLB/JSON, fall back to autogen-from-diffuse.
        cancellationToken.ThrowIfCancellationRequested();
        var specularSrc = TryResolveChannelSource(material, jsonMaterial, "specular", ["MetallicRoughness"], "specular", out string? specWarn);
        if (specWarn != null) warnings.Add(specWarn);
        ResolvedChannelSource? specularChannel = null;
        bool generatedSpecular = false;
        if (specularSrc != null)
        {
            specularChannel = new ResolvedChannelSource(
                "specular",
                specularSrc.EncodedImageBytes,
                specularSrc.SourceIsDds,
                specularSrc.ImageName,
                NeedsAlpha: ChannelNeedsAlpha("specular", jsonMaterial),
                IsLightmapChannel: false,
                GenerateMipMaps: generateMipMaps);
        }
        else if (diffuseSrc != null)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();
                byte[] specularPng = DerivedTextureGenerator.GenerateSpecularMapPngFromImage(diffuseSrc.EncodedImageBytes);
                string generatedName = BuildGeneratedImageName(diffuseSrc.ImageName, "autogen_specular_linear_v1");
                specularChannel = new ResolvedChannelSource(
                    "specular",
                    specularPng,
                    SourceIsDds: false,
                    ImageName: generatedName,
                    NeedsAlpha: false,
                    IsLightmapChannel: false,
                    GenerateMipMaps: generateMipMaps);
                generatedSpecular = true;
            }
            catch (Exception ex)
            {
                warnings.Add($"Auto-generated specular map skipped: {ex.Message}");
            }
        }

        string? attributorStream = jsonMaterial != null ? jsonMaterial.MaterialName : null;
        var channelConfig = BlenroseMaterialJsonReader.ToChannelConfig(jsonMaterial);
        channelConfig = EnsureGeneratedChannelsInConfig(channelConfig, generatedNormal, generatedSpecular);

        return new ResolvedGlbTextureSources(
            glbPath,
            glbIdentity,
            materialName,
            diffuseChannel,
            normalChannel,
            lightmapChannel,
            specularChannel,
            generatedNormal,
            generatedSpecular,
            attributorStream,
            channelConfig,
            warnings);
    }

    /// <summary>
    /// In-memory sibling of <see cref="ResolveSourcesFromGlb"/>. Builds a
    /// <see cref="ResolvedGlbTextureSources"/> from raw PNG/JPG/DDS bytes per channel
    /// instead of loading them out of a GLB on disk. Generic (no GLB file I/O):
    /// callers provide whatever channels they have, and missing normal/specular maps
    /// are auto-synthesised from the diffuse exactly the same way the GLB path does.
    /// A null diffuse with non-null derived channels is permitted but unusual —
    /// autogen requires the diffuse bytes. (No surviving caller after the Godot
    /// direct-feed path was removed; retained as a generic helper.)
    /// </summary>
    /// <param name="sourceKey">Opaque per-source identifier used as the equivalent of
    ///     <c>glbPath</c> in deduplication / lookup keys. Stable across builds → stable GUIDs.</param>
    /// <param name="materialName">Material name written into the mesh PSG override and into
    ///     the texture GUID derivation. Required.</param>
    /// <param name="diffusePng">PNG/JPG/DDS bytes for the BaseColor channel, or null.</param>
    /// <param name="normalPng">Explicit normal-map bytes, or null to autogen from diffuse.</param>
    /// <param name="lightmapPng">Lightmap bytes, or null. No fallback — engines that need a
    ///     lightmap and get none use their internal default texture.</param>
    /// <param name="specularPng">Explicit specular bytes, or null to autogen from diffuse.</param>
    public static ResolvedGlbTextureSources ResolveSourcesFromBytes(
        string sourceKey,
        string materialName,
        byte[]? diffusePng,
        byte[]? normalPng = null,
        byte[]? lightmapPng = null,
        byte[]? specularPng = null,
        bool generateMipMaps = true,
        string? guidNamespace = null,
        DerivedTextureGenerator.NormalSynthSettings? normalSynthSettings = null,
        string? attributorMaterialName = null,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(sourceKey))
            throw new ArgumentException("sourceKey is required.", nameof(sourceKey));
        if (string.IsNullOrWhiteSpace(materialName))
            throw new ArgumentException("materialName is required.", nameof(materialName));

        var warnings = new List<string>();
        string identity = BuildScopedGlbIdentity(sourceKey, sourceKey, guidNamespace);

        // A transparent/alpha AttributorMaterial (e.g. environment.transparent)
        // means the engine's shader samples the diffuse alpha — so the diffuse
        // PNG must encode as DXT5 (alpha-preserving), not DXT1. Without this the
        // alpha never ships and the mesh renders fully opaque no matter which
        // material class it was tagged with.
        bool diffuseNeedsAlpha = AttributorWantsDiffuseAlpha(attributorMaterialName);

        // Diffuse — used both directly and as the source for autogen normal/specular.
        ResolvedChannelSource? diffuseChannel = null;
        if (diffusePng != null && diffusePng.Length > 0)
        {
            diffuseChannel = new ResolvedChannelSource(
                "diffuse",
                diffusePng,
                SourceIsDds: false,
                ImageName: $"{materialName}_diffuse",
                NeedsAlpha: diffuseNeedsAlpha,
                IsLightmapChannel: false,
                GenerateMipMaps: generateMipMaps);
        }

        // Normal — explicit, else autogen, else skip.
        cancellationToken.ThrowIfCancellationRequested();
        ResolvedChannelSource? normalChannel = null;
        bool generatedNormal = false;
        if (normalPng != null && normalPng.Length > 0)
        {
            normalChannel = new ResolvedChannelSource(
                "normal",
                normalPng,
                SourceIsDds: false,
                ImageName: $"{materialName}_normal",
                NeedsAlpha: false,
                IsLightmapChannel: false,
                GenerateMipMaps: generateMipMaps);
        }
        else if (diffuseChannel != null)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();
                var synthSettings = normalSynthSettings ?? DerivedTextureGenerator.DefaultNormalSettings;
                // Memoized by diffuse content hash. A build uses one settings
                // instance for every source, so the hash need not fold it in.
                byte[] genPng = AutogenCache.GetOrAdd(
                    ContentKey("nrm", diffuseChannel.EncodedImageBytes),
                    _ => DerivedTextureGenerator.GenerateNormalMapPngFromImage(diffuseChannel.EncodedImageBytes, synthSettings));
                string generatedName = BuildGeneratedImageName(diffuseChannel.ImageName, "autogen_normal_sobel_v1");
                normalChannel = new ResolvedChannelSource(
                    "normal",
                    genPng,
                    SourceIsDds: false,
                    ImageName: generatedName,
                    NeedsAlpha: false,
                    IsLightmapChannel: false,
                    GenerateMipMaps: generateMipMaps);
                generatedNormal = true;
            }
            catch (Exception ex)
            {
                warnings.Add($"Auto-generated normal map skipped: {ex.Message}");
            }
        }

        // Lightmap — no autogen. Forced single-mip to match retail PS3 lightmap output.
        cancellationToken.ThrowIfCancellationRequested();
        ResolvedChannelSource? lightmapChannel = null;
        if (lightmapPng != null && lightmapPng.Length > 0)
        {
            lightmapChannel = new ResolvedChannelSource(
                "lightmap",
                lightmapPng,
                SourceIsDds: false,
                ImageName: $"{materialName}_lightmap",
                NeedsAlpha: false,
                IsLightmapChannel: true,
                GenerateMipMaps: false);
        }

        // Specular — explicit, else autogen from diffuse, else skip.
        cancellationToken.ThrowIfCancellationRequested();
        ResolvedChannelSource? specularChannel = null;
        bool generatedSpecular = false;
        if (specularPng != null && specularPng.Length > 0)
        {
            specularChannel = new ResolvedChannelSource(
                "specular",
                specularPng,
                SourceIsDds: false,
                ImageName: $"{materialName}_specular",
                NeedsAlpha: false,
                IsLightmapChannel: false,
                GenerateMipMaps: generateMipMaps);
        }
        else if (diffuseChannel != null)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();
                byte[] genPng = AutogenCache.GetOrAdd(
                    ContentKey("spec", diffuseChannel.EncodedImageBytes),
                    _ => DerivedTextureGenerator.GenerateSpecularMapPngFromImage(diffuseChannel.EncodedImageBytes));
                string generatedName = BuildGeneratedImageName(diffuseChannel.ImageName, "autogen_specular_linear_v1");
                specularChannel = new ResolvedChannelSource(
                    "specular",
                    genPng,
                    SourceIsDds: false,
                    ImageName: generatedName,
                    NeedsAlpha: false,
                    IsLightmapChannel: false,
                    GenerateMipMaps: generateMipMaps);
                generatedSpecular = true;
            }
            catch (Exception ex)
            {
                warnings.Add($"Auto-generated specular map skipped: {ex.Message}");
            }
        }

        return new ResolvedGlbTextureSources(
            sourceKey,
            identity,
            materialName,
            diffuseChannel,
            normalChannel,
            lightmapChannel,
            specularChannel,
            generatedNormal,
            generatedSpecular,
            AttributorMaterialStream: string.IsNullOrWhiteSpace(attributorMaterialName)
                ? null
                : attributorMaterialName,
            ChannelConfig: null,
            ResolveWarnings: warnings);
    }

    /// <summary>
    /// True when an AttributorMaterialName's subclass samples the diffuse alpha
    /// channel (transparent / alpha / alphatest families). Mirrors BlenRose's
    /// alpha-aware subclasses; drives DXT5-vs-DXT1 selection for the diffuse.
    /// </summary>
    private static bool AttributorWantsDiffuseAlpha(string? attributorMaterialName)
    {
        if (string.IsNullOrWhiteSpace(attributorMaterialName))
            return false;
        string name = attributorMaterialName!;
        int dot = name.IndexOf('.');
        string sub = dot >= 0 ? name[(dot + 1)..] : name;
        return sub.Equals("transparent", StringComparison.OrdinalIgnoreCase)
            || sub.Equals("alpha", StringComparison.OrdinalIgnoreCase)
            || sub.Equals("alphatest", StringComparison.OrdinalIgnoreCase)
            || sub.Equals("reflective_trans", StringComparison.OrdinalIgnoreCase)
            || sub.Equals("flowingalpha", StringComparison.OrdinalIgnoreCase)
            || sub.Equals("skatepark_alpha", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Computes the deterministic FULL-variant GUID for a mesh-bound channel: the GUID has
    /// <see cref="TextureGuidStrategy.SmallVariantFlag"/> (bit 62) cleared so it is safe to use
    /// as a mesh-channel reference. The engine resolves the full copy from cTex via this GUID,
    /// or — on a primary lookup miss — sets bit 62 and resolves the small copy from cPres.
    /// </summary>
    public static ulong ComputeChannelFullGuid(
        ResolvedGlbTextureSources sources,
        ResolvedChannelSource channel)
    {
        if (sources is null) throw new ArgumentNullException(nameof(sources));
        if (channel is null) throw new ArgumentNullException(nameof(channel));
        string textureKey = TextureGuidStrategy.BuildTextureKey(
            sources.GlbIdentity,
            sources.MaterialName,
            channel.MeshChannelName,
            channel.ImageName);
        return TextureGuidStrategy.KeyToGuid(textureKey);
    }

    /// <summary>
    /// Default linear downscale factor applied to the small (cPres) fallback variant.
    /// Empirically the stock <c>DLC_DW_MegaCompund</c> distribution pairs every full↔small
    /// sibling as exactly 8× linear (= 64× pixels), e.g. 512×512 ↔ 64×64, 256×128 ↔ 32×16.
    /// </summary>
    public const int DefaultSmallVariantDownscaleFactor = 8;

    /// <summary>
    /// Lower bound on the small variant's longest side, regardless of source dimensions.
    /// 8 px keeps DXT 4×4-block encoding valid for both axes.
    /// </summary>
    public const int DefaultSmallVariantMinDim = 8;

    /// <summary>
    /// Controls how the lightmap channel is routed relative to the dual-tier (small cPres +
    /// full cTex) scheme used by every other channel.
    /// </summary>
    /// <remarks>
    /// Skate 3's engine loads lightmap PSGs out of the per-tile <c>cPres_&lt;X&gt;_&lt;Y&gt;_high</c>
    /// collection (resident with that tile's geometry), NOT the streaming
    /// <c>cTex_&lt;X&gt;_&lt;Y&gt;_high</c> collection. So lightmaps must be full-resolution and
    /// must live in cPres, never cTex — the opposite of the diffuse/normal/specular dual-tier
    /// policy.
    /// </remarks>
    /// <summary>Per-channel emit decision returned by a
    /// <see cref="ChannelPlacementResolver"/>. Lets the budget planner in
    /// <c>ArenaBuilder.Build</c> drive placement without this Texture-layer
    /// type referencing any Glb tile-grid types.</summary>
    public enum ChannelEmitDecision
    {
        /// <summary>Don't write this channel into this tile at all (promoted
        /// elsewhere, or cTex-budget-rejected).</summary>
        Skip,
        /// <summary>Write the SMALL (mip-sliced) fallback under the
        /// bit-62-set sibling GUID.</summary>
        Small,
        /// <summary>Write the FULL-resolution copy under the full GUID.</summary>
        Full,
    }

    /// <summary>Resolver the pipeline supplies so the budget plan (which
    /// knows tile geometry) decides each channel's fate for the tile being
    /// emitted. <c>fullGuid</c> is the channel's full-variant GUID;
    /// <c>isLightmapChannel</c> lets the resolver keep the lightmap-specific
    /// rules. Return <see cref="ChannelEmitDecision"/>.</summary>
    public delegate ChannelEmitDecision ChannelPlacementResolver(ulong fullGuid, bool isLightmapChannel);

    public enum LightmapEmitMode
    {
        /// <summary>
        /// Lightmap channel follows the same variant policy as every other channel
        /// (full-res in a full-variant emit, 1/8 small in a small-variant emit). This is the
        /// legacy behaviour; correct for GlobalOnly's single self-contained collection.
        /// </summary>
        Default,

        /// <summary>
        /// Skip the lightmap channel entirely for this emit. Used when writing a streaming
        /// <c>cTex_*</c> tile: lightmaps must not appear in cTex.
        /// </summary>
        SkipLightmap,

        /// <summary>
        /// Emit the lightmap channel at FULL resolution under the FULL GUID (bit 62 clear),
        /// even though the rest of this emit is a small (cPres) variant. The mesh material ref
        /// points at the FULL GUID; with no cTex copy in existence the engine's primary lookup
        /// must resolve directly out of this cPres tile, so the cPres copy has to be the
        /// full-res, full-GUID one.
        /// </summary>
        CPresFullResLightmap,
    }

    /// <summary>
    /// Phase 2 of the texture build — emits one Texture PSG per channel of <paramref name="sources"/>
    /// into <paramref name="outputDirectory"/> under the FULL-variant GUID
    /// (<see cref="ComputeChannelFullGuid"/>; bit 62 cleared). Use this for cTex tiles AND for
    /// GlobalOnly's single self-contained collection — anywhere the texture lives at full resolution.
    /// </summary>
    /// <param name="lightmapMode">
    /// For cTex tiles pass <see cref="LightmapEmitMode.SkipLightmap"/> (lightmaps never go to
    /// cTex). For GlobalOnly's self-contained collection leave it
    /// <see cref="LightmapEmitMode.Default"/> (the whole map is resident, so the lightmap can
    /// live next to everything else at full res).
    /// </param>
    /// <remarks>
    /// The encode-once cache means BCn runs at most ONE time per (sourceBytes, encode flags,
    /// maxDim) tuple across the whole build, regardless of how many cTex tiles end up calling this.
    /// </remarks>
    public static GlbTextureAutoBuildResult EmitFullToTile(
        ResolvedGlbTextureSources sources,
        string outputDirectory,
        TextureDeduplicationRegistry deduplicationRegistry,
        LightmapEmitMode lightmapMode = LightmapEmitMode.Default,
        CancellationToken cancellationToken = default)
        => EmitVariantToTile(
            sources,
            outputDirectory,
            deduplicationRegistry,
            isSmallVariant: false,
            smallDownscaleFactor: 0,
            smallMinDim: 0,
            lightmapMode,
            cancellationToken);

    /// <summary>
    /// Phase 2 of the texture build — emits one Texture PSG per channel of <paramref name="sources"/>
    /// into <paramref name="outputDirectory"/> under the SMALL-variant GUID
    /// (full GUID with <see cref="TextureGuidStrategy.SmallVariantFlag"/> set). Use this for the
    /// per-cPres-tile fallback copies. Each channel is downscaled to
    /// <c>max(smallMinDim, max(srcW, srcH) / smallDownscaleFactor)</c> on its longest side, mirroring
    /// the empirical 1/8-linear pairing observed in stock content.
    /// </summary>
    /// <param name="lightmapMode">
    /// For per-tile cPres emits pass <see cref="LightmapEmitMode.CPresFullResLightmap"/>: the
    /// lightmap channel is then written full-res under the FULL GUID (bit 62 clear) so the
    /// engine's primary lookup resolves it straight out of this cPres tile, while
    /// diffuse/normal/specular still get the 1/8 small fallback treatment.
    /// </param>
    public static GlbTextureAutoBuildResult EmitSmallToTile(
        ResolvedGlbTextureSources sources,
        string outputDirectory,
        TextureDeduplicationRegistry deduplicationRegistry,
        int smallDownscaleFactor = DefaultSmallVariantDownscaleFactor,
        int smallMinDim = DefaultSmallVariantMinDim,
        LightmapEmitMode lightmapMode = LightmapEmitMode.CPresFullResLightmap,
        CancellationToken cancellationToken = default)
        => EmitVariantToTile(
            sources,
            outputDirectory,
            deduplicationRegistry,
            isSmallVariant: true,
            smallDownscaleFactor: Math.Max(1, smallDownscaleFactor),
            smallMinDim: Math.Max(1, smallMinDim),
            lightmapMode,
            cancellationToken);

    /// <summary>
    /// Budget-planned emit. The <paramref name="placement"/> resolver decides
    /// Skip / Small / Full per channel for the specific tile this call writes
    /// into. Used by the Stage-2 budget pipeline; for GlobalOnly the legacy
    /// <see cref="EmitFullToTile"/> path (no resolver) still applies.
    /// </summary>
    public static GlbTextureAutoBuildResult EmitPlanned(
        ResolvedGlbTextureSources sources,
        string outputDirectory,
        TextureDeduplicationRegistry deduplicationRegistry,
        ChannelPlacementResolver placement,
        int smallDownscaleFactor = DefaultSmallVariantDownscaleFactor,
        int smallMinDim = DefaultSmallVariantMinDim,
        CancellationToken cancellationToken = default)
        => EmitVariantToTile(
            sources,
            outputDirectory,
            deduplicationRegistry,
            isSmallVariant: false,
            smallDownscaleFactor: Math.Max(1, smallDownscaleFactor),
            smallMinDim: Math.Max(1, smallMinDim),
            LightmapEmitMode.Default,
            placement,
            cancellationToken);

    /// <summary>
    /// Resolve a source's channels and report each one's full GUID, encoded
    /// payload size, and lightmap flag — WITHOUT writing any PSG. Drives the
    /// Stage-2 budget plan. The full encode it triggers is cached, so the
    /// subsequent <see cref="EmitPlanned"/> pass reuses it for free.
    /// </summary>
    public static IReadOnlyList<(string ChannelName, ulong FullGuid, long PayloadSize, bool IsLightmap)> MeasureChannels(
        ResolvedGlbTextureSources sources,
        TextureDeduplicationRegistry deduplicationRegistry,
        CancellationToken cancellationToken = default)
    {
        var outList = new List<(string, ulong, long, bool)>(4);
        Measure(sources.Diffuse);
        Measure(sources.Normal);
        Measure(sources.Lightmap);
        Measure(sources.Specular);
        return outList;

        void Measure(ResolvedChannelSource? channel)
        {
            if (channel == null) return;
            cancellationToken.ThrowIfCancellationRequested();
            bool isNormalChannel = string.Equals(channel.MeshChannelName, "normal", StringComparison.OrdinalIgnoreCase);
            bool preserveAlpha = channel.NeedsAlpha && !isNormalChannel;
            bool reduceBc1NormalArtifacts = isNormalChannel && !channel.SourceIsDds;
            try
            {
                var dds = deduplicationRegistry.GetOrEncode(
                    channel.EncodedImageBytes,
                    channel.SourceIsDds,
                    channel.GenerateMipMaps,
                    preserveAlpha,
                    forceOpaqueAlpha: isNormalChannel,
                    reduceBc1NormalArtifacts: reduceBc1NormalArtifacts,
                    maxDimension: null);
                // Stage 3: content-addressed GUID — derived from the encoded
                // DDS, NOT the GLB/material/channel path. Identical content
                // anywhere → one GUID → one PSG (global dedup).
                ulong fullGuid = TextureGuidStrategy.ContentAddressedFullGuid(dds);
                outList.Add((channel.MeshChannelName, fullGuid, dds.Payload.LongLength, channel.IsLightmapChannel));
            }
            catch
            {
                // Measurement failure (bad source). Fall back to the legacy
                // path-based GUID so the planner still has a stable record;
                // the emit pass will log the real encode error and also fail
                // there, so this row simply never gets emitted.
                ulong fallbackGuid = ComputeChannelFullGuid(sources, channel);
                outList.Add((channel.MeshChannelName, fallbackGuid, 0L, channel.IsLightmapChannel));
            }
        }
    }

    private static GlbTextureAutoBuildResult EmitVariantToTile(
        ResolvedGlbTextureSources sources,
        string outputDirectory,
        TextureDeduplicationRegistry deduplicationRegistry,
        bool isSmallVariant,
        int smallDownscaleFactor,
        int smallMinDim,
        LightmapEmitMode lightmapMode,
        CancellationToken cancellationToken)
        => EmitVariantToTile(
            sources, outputDirectory, deduplicationRegistry, isSmallVariant,
            smallDownscaleFactor, smallMinDim, lightmapMode, placement: null, cancellationToken);

    private static GlbTextureAutoBuildResult EmitVariantToTile(
        ResolvedGlbTextureSources sources,
        string outputDirectory,
        TextureDeduplicationRegistry deduplicationRegistry,
        bool isSmallVariant,
        int smallDownscaleFactor,
        int smallMinDim,
        LightmapEmitMode lightmapMode,
        ChannelPlacementResolver? placement,
        CancellationToken cancellationToken)
    {
        if (sources is null) throw new ArgumentNullException(nameof(sources));
        if (deduplicationRegistry is null) throw new ArgumentNullException(nameof(deduplicationRegistry));
        if (string.IsNullOrWhiteSpace(outputDirectory))
            throw new ArgumentException("Output directory is required.", nameof(outputDirectory));

        Directory.CreateDirectory(outputDirectory);

        var built = new List<BuiltTexturePsg>();
        var warnings = new List<string>(sources.ResolveWarnings);

        ulong? diffuseGuid = EmitChannel(sources.Diffuse);
        ulong? normalGuid = EmitChannel(sources.Normal);
        ulong? lightmapGuid = EmitChannel(sources.Lightmap);
        ulong? specularGuid = EmitChannel(sources.Specular);

        return new GlbTextureAutoBuildResult(
            diffuseGuid,
            normalGuid,
            lightmapGuid,
            specularGuid,
            built,
            warnings,
            sources.AttributorMaterialStream,
            sources.ChannelConfig);

        // Returns the FULL-variant GUID for every channel (bit 62 clear) — that is what mesh
        // channels reference regardless of which variant we emitted into this tile. The engine
        // performs the small-variant retry by ORing bit 62 if the full lookup misses.
        ulong? EmitChannel(ResolvedChannelSource? channel)
        {
            if (channel == null) return null;
            cancellationToken.ThrowIfCancellationRequested();

            bool isNormalChannel = string.Equals(channel.MeshChannelName, "normal", StringComparison.OrdinalIgnoreCase);
            bool preserveAlpha = channel.NeedsAlpha && !isNormalChannel;
            bool reduceBc1NormalArtifacts = isNormalChannel && !channel.SourceIsDds;

            // SINGLE encode for this channel — full resolution, full mip
            // chain — shared across every tile via the encode-once cache.
            // Must run BEFORE the GUID/placement decision because Stage 3's
            // GUID is content-addressed (derived from the encoded DDS), so
            // there is nothing to key the plan on until the bytes exist.
            // The small (cPres) variant is a byte-slice of this chain, never
            // a second encode (port of BlenRose's _dds_pick_small_variant).
            DdsTextureInput fullDds;
            try
            {
                fullDds = deduplicationRegistry.GetOrEncode(
                    channel.EncodedImageBytes,
                    channel.SourceIsDds,
                    channel.GenerateMipMaps,
                    preserveAlpha,
                    forceOpaqueAlpha: isNormalChannel,
                    reduceBc1NormalArtifacts: reduceBc1NormalArtifacts,
                    maxDimension: null);
            }
            catch (Exception ex)
            {
                warnings.Add($"Encode failed for {sources.GlbPath} channel '{channel.MeshChannelName}': {ex.Message}");
                return null;
            }

            // Stage 3: content-addressed GUID — function of the encoded DDS
            // only (port of BlenRose _tex_guid_from_dedupe_key). Identical
            // content anywhere collapses to one GUID / one PSG.
            ulong fullGuid = TextureGuidStrategy.ContentAddressedFullGuid(fullDds);

            bool channelEmitsAsSmall = isSmallVariant;

            // Stage-2 budget plan resolver (when supplied) is authoritative:
            // decides Skip / Small / Full for THIS channel in THIS tile,
            // keyed on the content-addressed GUID computed above.
            if (placement != null)
            {
                ChannelEmitDecision decision = placement(fullGuid, channel.IsLightmapChannel);
                switch (decision)
                {
                    case ChannelEmitDecision.Skip:
                        // Don't write a PSG into THIS tile — but still report
                        // the full GUID so the mesh material binds it. The
                        // bytes live in cPres_Global (promoted) or a cTex tile
                        // (streamed); the engine's full-GUID lookup (with the
                        // bit-62 cPres fallback retry) resolves it at runtime.
                        return fullGuid;
                    case ChannelEmitDecision.Small:
                        channelEmitsAsSmall = true;
                        break;
                    case ChannelEmitDecision.Full:
                        channelEmitsAsSmall = false;
                        break;
                }
            }
            else if (channel.IsLightmapChannel)
            {
                // Legacy (GlobalOnly / no-plan) path: lightmap routing
                // overrides the dual-tier policy. Skate's engine pulls
                // lightmap PSGs out of the resident per-tile cPres
                // collection, never the streamed cTex one — a cTex emit
                // drops the lightmap; a per-tile cPres (small) emit promotes
                // it to full-res / full-GUID so the mesh ref's primary
                // lookup resolves straight out of that cPres tile.
                switch (lightmapMode)
                {
                    case LightmapEmitMode.SkipLightmap:
                        return null;
                    case LightmapEmitMode.CPresFullResLightmap:
                        channelEmitsAsSmall = false;
                        break;
                    case LightmapEmitMode.Default:
                    default:
                        break;
                }
            }

            DdsTextureInput ddsInput = fullDds;
            bool wroteSmall = false;
            if (channelEmitsAsSmall)
            {
                if (DdsMipSlicer.TrySliceSmallVariant(
                        fullDds, smallDownscaleFactor, smallMinDim, out DdsTextureInput? small)
                    && small != null)
                {
                    ddsInput = small;
                    wroteSmall = true;
                }
                else
                {
                    // No usable deeper mip (single-mip source, or already
                    // small enough that the slice level clamps to 0).
                    // BlenRose's `_resolve_small → None`: emit the FULL
                    // texture into the cPres tile under the FULL GUID. The
                    // mesh ref's primary lookup resolves it straight out of
                    // this resident tile; no broken tiny re-encode.
                    ddsInput = fullDds;
                    wroteSmall = false;
                }
            }

            ulong writeGuid = wroteSmall
                ? TextureGuidStrategy.MakeSmallVariantGuid(fullGuid)
                : fullGuid;

            var psg = deduplicationRegistry.WriteLogicalGuidPsg(
                ddsInput,
                writeGuid,
                channel.MeshChannelName,
                channel.ImageName,
                outputDirectory);
            built.Add(psg);
            return fullGuid;
        }
    }

    /// <summary>
    /// Phase 2 of the texture build: write up to four PSG files into <paramref name="outputDirectory"/>
    /// from a previously-<see cref="ResolveSourcesFromGlb">resolved</see> GLB. When a registry is
    /// supplied, BCn encoding runs at most once per (sourceBytes,flags) tuple per build (see
    /// <see cref="TextureDeduplicationRegistry.GetOrEncode"/>); identical PSGs within the same
    /// <paramref name="deduplicationScope"/> are deduplicated to a single GUID/file.
    ///
    /// Call this once per cPres tile that should hold a copy of the GLB's textures: pass a unique
    /// <paramref name="deduplicationScope"/> per tile (e.g. <c>"cpres|U|V"</c>) so that byte-identical
    /// content written into different tiles still gets distinct GUIDs — required by the new
    /// per-tile self-contained collection layout.
    /// </summary>
    public static GlbTextureAutoBuildResult EmitToTile(
        ResolvedGlbTextureSources sources,
        string outputDirectory,
        TextureDeduplicationRegistry? deduplicationRegistry = null,
        string? deduplicationScope = null,
        CancellationToken cancellationToken = default)
    {
        if (sources is null)
            throw new ArgumentNullException(nameof(sources));
        if (string.IsNullOrWhiteSpace(outputDirectory))
            throw new ArgumentException("Output directory is required.", nameof(outputDirectory));

        Directory.CreateDirectory(outputDirectory);

        var built = new List<BuiltTexturePsg>();
        var warnings = new List<string>(sources.ResolveWarnings);

        ulong? diffuseGuid = EmitChannel(sources.Diffuse);
        ulong? normalGuid = EmitChannel(sources.Normal);
        ulong? lightmapGuid = EmitChannel(sources.Lightmap);
        ulong? specularGuid = EmitChannel(sources.Specular);

        return new GlbTextureAutoBuildResult(
            diffuseGuid,
            normalGuid,
            lightmapGuid,
            specularGuid,
            built,
            warnings,
            sources.AttributorMaterialStream,
            sources.ChannelConfig);

        ulong? EmitChannel(ResolvedChannelSource? channel)
        {
            if (channel == null) return null;
            cancellationToken.ThrowIfCancellationRequested();
            var psg = BuildTextureFromEncodedSource(
                channel.EncodedImageBytes,
                channel.SourceIsDds,
                channel.ImageName,
                sources.GlbIdentity,
                sources.MaterialName,
                channel.MeshChannelName,
                outputDirectory,
                channel.GenerateMipMaps,
                deduplicationRegistry,
                channel.NeedsAlpha,
                channel.IsLightmapChannel,
                deduplicationScope);
            built.Add(psg);
            return psg.Guid;
        }
    }

    private static BuiltTexturePsg? TryBuildChannelTexture(
        Material material,
        string glbPath,
        string glbIdentity,
        string materialName,
        BlenroseMaterialJsonReader.MaterialTextureConfig? jsonMaterial,
        string jsonChannelName,
        string[] glbChannelNames,
        string meshChannelName,
        string outputDirectory,
        bool generateMipMaps,
        TextureDeduplicationRegistry? deduplicationRegistry,
        string? deduplicationScope,
        out ResolvedTextureSource? resolvedSource,
        out string? warning)
    {
        warning = null;
        resolvedSource = null;

        bool isLightmapChannel = string.Equals(meshChannelName, "lightmap", StringComparison.OrdinalIgnoreCase);
        bool needsAlpha = ChannelNeedsAlpha(meshChannelName, jsonMaterial);

        // Force single-mip export only for lightmaps.
        bool wantsMipMaps = generateMipMaps && !isLightmapChannel;

        resolvedSource = TryResolveChannelSource(material, jsonMaterial, jsonChannelName, glbChannelNames, meshChannelName, out warning);
        if (resolvedSource == null)
            return null;

        return BuildTextureFromEncodedSource(
            resolvedSource.EncodedImageBytes,
            resolvedSource.SourceIsDds,
            resolvedSource.ImageName,
            glbIdentity,
            materialName,
            meshChannelName,
            outputDirectory,
            wantsMipMaps,
            deduplicationRegistry,
            needsAlpha,
            isLightmapChannel,
            deduplicationScope);
    }

    private static BuiltTexturePsg? TryBuildChannelTextureFromGlb(
        Material material,
        string glbIdentity,
        string materialName,
        string glbChannelName,
        string meshChannelName,
        string outputDirectory,
        bool generateMipMaps,
        TextureDeduplicationRegistry? deduplicationRegistry,
        bool needsAlpha,
        bool isLightmapChannel,
        out string? warning,
        string? deduplicationScope = null)
    {
        warning = null;
        try
        {
            var texture = material.FindChannel(glbChannelName)?.Texture;
            if (texture == null) return null;

            var image = texture.PrimaryImage ?? texture.FallbackImage;
            if (image == null) return null;

            MemoryImage content = image.Content;
            byte[] encodedImageBytes = ReadAllBytes(content);
            bool sourceIsDds = content.IsDds;
            string imageName = ResolveImageName(image, content, meshChannelName);

            return BuildTextureFromEncodedSource(
                encodedImageBytes,
                sourceIsDds,
                imageName,
                glbIdentity,
                materialName,
                meshChannelName,
                outputDirectory,
                generateMipMaps,
                deduplicationRegistry,
                needsAlpha,
                isLightmapChannel,
                deduplicationScope);
        }
        catch (Exception ex)
        {
            warning = $"Texture build skipped for GLB channel '{meshChannelName}': {ex.Message}";
            return null;
        }
    }

    private static BuiltTexturePsg BuildTextureFromEncodedSource(
        byte[] encodedImageBytes,
        bool sourceIsDds,
        string imageName,
        string glbIdentity,
        string materialName,
        string meshChannelName,
        string outputDirectory,
        bool generateMipMaps,
        TextureDeduplicationRegistry? deduplicationRegistry,
        bool needsAlpha,
        bool isLightmapChannel,
        string? deduplicationScope = null)
    {
        // For DDS sources we trust the author's chosen format and mip layout.
        // For raster sources we choose DXT1 vs DXT5 and honor caller mip behavior.
        //
        // Shipped PS3 normal textures are plain opaque BC1/DXT1 in the samples we inspected.
        // Treat raster normal maps as opaque so incidental PNG alpha does not turn BC1 blocks
        // into transparent-black artifacts.
        bool isNormalChannel =
            string.Equals(meshChannelName, "normal", StringComparison.OrdinalIgnoreCase);
        bool preserveAlpha = needsAlpha && !isNormalChannel;
        bool reduceBc1NormalArtifacts = isNormalChannel && !sourceIsDds;

        // Encode-once: when the registry is provided, identical (sourceBytes + flags) reuse the
        // parsed DDS that was encoded the first time we saw this content in this build, even
        // across different per-tile dedup scopes (which all produce distinct GUIDs/PSGs but share
        // one DDS payload).
        DdsTextureInput ddsInput;
        if (deduplicationRegistry != null)
        {
            ddsInput = deduplicationRegistry.GetOrEncode(
                encodedImageBytes,
                sourceIsDds,
                generateMipMaps,
                preserveAlpha,
                forceOpaqueAlpha: isNormalChannel,
                reduceBc1NormalArtifacts: reduceBc1NormalArtifacts);

            return deduplicationRegistry.RegisterOrReuse(
                ddsInput,
                meshChannelName,
                imageName,
                outputDirectory,
                deduplicationScope);
        }

        // No registry: encode and write inline (callers without a per-build cache use this path,
        // mostly the standalone CLI).
        byte[] ddsBytes = sourceIsDds
            ? encodedImageBytes
            : ImageToDdsConverter.ConvertToDds(
                encodedImageBytes,
                generateMipMaps,
                preserveAlpha,
                forceOpaqueAlpha: isNormalChannel,
                bc1NormalMapArtifactReduction: reduceBc1NormalArtifacts);
        ddsInput = DdsReader.Read(ddsBytes);

        // Without a registry there is no cross-call dedup. Fold the scope into the texture key so
        // that the same logical GLB texture, when emitted to two different output dirs, still gets
        // distinct GUIDs (each dir is a self-contained cPres tile in the new pipeline).
        string scopedIdentity = string.IsNullOrEmpty(deduplicationScope)
            ? glbIdentity
            : $"{deduplicationScope}|{glbIdentity}";
        string textureKey = TextureGuidStrategy.BuildTextureKey(scopedIdentity, materialName, meshChannelName, imageName);
        ulong textureGuid = TextureGuidStrategy.KeyToGuid(textureKey);
        string outPath = Path.Combine(outputDirectory, $"{textureGuid:X16}.psg");

        var spec = TexturePsgComposer.Compose(ddsInput, textureGuid);
        object writeLock = OutputWriteLocks.GetOrAdd(outPath, _ => new object());
        lock (writeLock)
        {
            using var fs = File.Create(outPath);
            GenericArenaWriter.Write(spec, fs);
        }

        return new BuiltTexturePsg(meshChannelName, imageName, ddsInput.Width, ddsInput.Height, textureGuid, outPath);
    }

    private static string BuildScopedGlbIdentity(string glbPath, string glbStem, string? guidNamespace)
    {
        if (string.IsNullOrWhiteSpace(guidNamespace))
            return glbStem;

        string fullGlbPath = Path.GetFullPath(glbPath).Replace('\\', '/').ToLowerInvariant();
        string fullNamespace = Path.GetFullPath(guidNamespace).Replace('\\', '/').ToLowerInvariant().TrimEnd('/');
        string relative = Path.GetRelativePath(fullNamespace, fullGlbPath).Replace('\\', '/').ToLowerInvariant();
        if (relative.StartsWith("../", StringComparison.Ordinal))
            relative = Path.GetFileNameWithoutExtension(fullGlbPath);
        return $"{fullNamespace}/{relative}";
    }

    private static BlenroseMaterialJsonReader.MaterialTextureConfig? TryResolveJsonMaterialConfig(
        string glbPath,
        string? materialsJsonPath,
        string materialName,
        string glbStem,
        List<string> warnings)
    {
        string? resolvedJsonPath = ResolveMaterialsJsonPath(glbPath, materialsJsonPath);
        if (resolvedJsonPath == null)
            return null;

        if (!File.Exists(resolvedJsonPath))
        {
            if (!string.IsNullOrWhiteSpace(materialsJsonPath))
                warnings.Add($"Materials JSON not found: {resolvedJsonPath}. Falling back to GLB textures.");
            return null;
        }

        IReadOnlyDictionary<string, BlenroseMaterialJsonReader.MaterialTextureConfig> byName;
        try
        {
            byName = BlenroseMaterialJsonReader.Read(resolvedJsonPath);
        }
        catch (Exception ex)
        {
            warnings.Add($"Failed to read materials JSON '{resolvedJsonPath}': {ex.Message}. Falling back to GLB textures.");
            return null;
        }

        if (byName.TryGetValue(materialName, out var matched))
            return matched;
        if (byName.TryGetValue(glbStem, out matched))
            return matched;

        // If exactly one unique material exists, use it as a pragmatic fallback.
        var unique = new List<BlenroseMaterialJsonReader.MaterialTextureConfig>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var candidate in byName.Values)
        {
            if (seen.Add(candidate.MaterialName))
                unique.Add(candidate);
        }

        if (unique.Count == 1)
        {
            warnings.Add($"Materials JSON had no entry for '{materialName}'. Using sole JSON material '{unique[0].MaterialName}'.");
            return unique[0];
        }

        warnings.Add($"Materials JSON had no entry for '{materialName}'. Using GLB textures for this material.");
        return null;
    }

    private static string? ResolveMaterialsJsonPath(string glbPath, string? materialsJsonPath)
    {
        if (!string.IsNullOrWhiteSpace(materialsJsonPath))
            return Path.GetFullPath(materialsJsonPath);

        string sidecarPath = Path.ChangeExtension(Path.GetFullPath(glbPath), ".json");
        return File.Exists(sidecarPath) ? sidecarPath : null;
    }

    private static string? TryGetJsonChannelImageName(
        BlenroseMaterialJsonReader.MaterialTextureConfig? jsonMaterial,
        string channelName)
    {
        if (jsonMaterial == null)
            return null;
        if (!jsonMaterial.ChannelImageNames.TryGetValue(channelName, out string? name))
            return null;
        return string.IsNullOrWhiteSpace(name) ? null : name;
    }

    private static readonly string[] KnownGlbChannels = ["BaseColor", "Normal", "Emissive", "Occlusion", "MetallicRoughness"];

    private static ResolvedTextureSource? TryResolveChannelSource(
        Material material,
        BlenroseMaterialJsonReader.MaterialTextureConfig? jsonMaterial,
        string jsonChannelName,
        string[] glbChannelNames,
        string meshChannelName,
        out string? warning)
    {
        warning = null;

        // 1) Resolve by JSON image_name hint.
        string? imageNameHint = TryGetJsonChannelImageName(jsonMaterial, jsonChannelName);
        if (!string.IsNullOrWhiteSpace(imageNameHint))
        {
            var sourceByName = TryResolveTextureSourceByImageName(material, imageNameHint, meshChannelName, out string? byNameWarning);
            if (sourceByName != null)
                return sourceByName;
            if (byNameWarning != null)
                warning = warning == null ? byNameWarning : $"{warning} | {byNameWarning}";
        }

        // 2) Fallback to GLB channel texture.
        foreach (var glbChannelName in glbChannelNames)
        {
            var sourceFromChannel = TryResolveTextureSourceFromGlbChannel(material, glbChannelName, meshChannelName, out string? glbWarning);
            if (sourceFromChannel != null)
                return sourceFromChannel;
            if (glbWarning != null)
                warning = warning == null ? glbWarning : $"{warning} | GLB {glbChannelName}: {glbWarning}";
        }

        return null;
    }

    private static ResolvedTextureSource? TryResolveTextureSourceFromGlbChannel(
        Material material,
        string glbChannelName,
        string meshChannelName,
        out string? warning)
    {
        warning = null;
        try
        {
            var texture = material.FindChannel(glbChannelName)?.Texture;
            if (texture == null) return null;

            var image = texture.PrimaryImage ?? texture.FallbackImage;
            if (image == null) return null;

            MemoryImage content = image.Content;
            byte[] encodedImageBytes = ReadAllBytes(content);
            bool sourceIsDds = content.IsDds;
            string imageName = ResolveImageName(image, content, meshChannelName);
            return new ResolvedTextureSource(encodedImageBytes, sourceIsDds, imageName);
        }
        catch (Exception ex)
        {
            warning = $"Texture source read skipped for GLB channel '{meshChannelName}': {ex.Message}";
            return null;
        }
    }

    private static ResolvedTextureSource? TryResolveTextureSourceByImageName(
        Material material,
        string imageNameHint,
        string meshChannelName,
        out string? warning)
    {
        warning = null;
        try
        {
            string hintNormalized = NormalizeImageNameForCompare(imageNameHint);
            foreach (var channelName in KnownGlbChannels)
            {
                var texture = material.FindChannel(channelName)?.Texture;
                if (texture == null) continue;

                var image = texture.PrimaryImage ?? texture.FallbackImage;
                if (image == null) continue;

                string texName = image.Name ?? "";
                if (string.IsNullOrWhiteSpace(texName) && !string.IsNullOrWhiteSpace(image.Content.SourcePath))
                    texName = Path.GetFileNameWithoutExtension(image.Content.SourcePath);
                if (string.IsNullOrWhiteSpace(texName))
                    continue;

                string texNameNormalized = NormalizeImageNameForCompare(texName);
                if (!string.Equals(texNameNormalized, hintNormalized, StringComparison.OrdinalIgnoreCase) &&
                    !texNameNormalized.Contains(hintNormalized))
                {
                    continue;
                }

                MemoryImage content = image.Content;
                byte[] encodedImageBytes = ReadAllBytes(content);
                bool sourceIsDds = content.IsDds;
                string imageName = ResolveImageName(image, content, meshChannelName);
                return new ResolvedTextureSource(encodedImageBytes, sourceIsDds, imageName);
            }
        }
        catch (Exception ex)
        {
            warning = $"Texture by name '{imageNameHint}' failed: {ex.Message}";
        }

        return null;
    }

    private static BuiltTexturePsg? TryBuildChannelTextureFromGlbByImageName(
        Material material,
        string glbIdentity,
        string materialName,
        string imageNameHint,
        string meshChannelName,
        string outputDirectory,
        bool generateMipMaps,
        TextureDeduplicationRegistry? deduplicationRegistry,
        bool needsAlpha,
        bool isLightmapChannel,
        out string? warning)
    {
        warning = null;
        try
        {
            string hintNormalized = NormalizeImageNameForCompare(imageNameHint);
            foreach (var channelName in KnownGlbChannels)
            {
                var texture = material.FindChannel(channelName)?.Texture;
                if (texture == null) continue;

                var image = texture.PrimaryImage ?? texture.FallbackImage;
                if (image == null) continue;

                string texName = image.Name ?? "";
                if (string.IsNullOrWhiteSpace(texName) && !string.IsNullOrWhiteSpace(image.Content.SourcePath))
                    texName = Path.GetFileNameWithoutExtension(image.Content.SourcePath);
                if (string.IsNullOrWhiteSpace(texName))
                    continue;

                string texNameNormalized = NormalizeImageNameForCompare(texName);

                if (string.Equals(texNameNormalized, hintNormalized, StringComparison.OrdinalIgnoreCase) ||
                    texNameNormalized.Contains(hintNormalized))
                {
                    MemoryImage content = image.Content;
                    byte[] encodedImageBytes = ReadAllBytes(content);
                    bool sourceIsDds = content.IsDds;
                    string imageName = ResolveImageName(image, content, meshChannelName);

                    return BuildTextureFromEncodedSource(
                        encodedImageBytes,
                        sourceIsDds,
                        imageName,
                        glbIdentity,
                        materialName,
                        meshChannelName,
                        outputDirectory,
                        generateMipMaps,
                        deduplicationRegistry,
                        needsAlpha,
                        isLightmapChannel);
                }
            }
        }
        catch (Exception ex)
        {
            warning = $"Texture by name '{imageNameHint}' failed: {ex.Message}";
        }
        return null;
    }

    private static string BuildGeneratedImageName(string baseImageName, string suffix)
    {
        string seed = string.IsNullOrWhiteSpace(baseImageName) ? "diffuse" : baseImageName.Trim();
        return $"{seed}__{suffix}";
    }

    private static RenderMaterialDataBuilder.BlenroseChannelConfig? EnsureGeneratedChannelsInConfig(
        RenderMaterialDataBuilder.BlenroseChannelConfig? channelConfig,
        bool addNormal,
        bool addSpecular)
    {
        if (channelConfig == null || (!addNormal && !addSpecular))
            return channelConfig;

        var channels = new HashSet<string>(channelConfig.TextureChannelNames, StringComparer.OrdinalIgnoreCase);
        bool changed = false;
        if (addNormal)
            changed |= channels.Add("normal");
        if (addSpecular)
            changed |= channels.Add("specular");
        if (!changed)
            return channelConfig;

        string[] order = ["environment", "lightmap", "decal", "specular", "diffuse", "detail", "macrooverlay", "normal", "transparent", "noise"];
        var merged = new List<string>();
        foreach (var name in order)
        {
            if (channels.Contains(name))
                merged.Add(name);
        }

        // Preserve any unknown/custom names after canonical channels.
        foreach (var name in channelConfig.TextureChannelNames)
        {
            if (!merged.Contains(name, StringComparer.OrdinalIgnoreCase))
                merged.Add(name);
        }
        foreach (var name in channels)
        {
            if (!merged.Contains(name, StringComparer.OrdinalIgnoreCase))
                merged.Add(name);
        }

        return new RenderMaterialDataBuilder.BlenroseChannelConfig(merged, channelConfig.ScalarValues);
    }

    private static string NormalizeImageNameForCompare(string imageName)
    {
        string trimmed = imageName.Trim();
        if (string.IsNullOrWhiteSpace(trimmed))
            return string.Empty;
        return Path.GetFileNameWithoutExtension(trimmed).Trim().ToLowerInvariant();
    }

    private static bool ChannelNeedsAlpha(
        string meshChannelName,
        BlenroseMaterialJsonReader.MaterialTextureConfig? jsonMaterial)
    {
        // Transparent channel always uses alpha.
        if (string.Equals(meshChannelName, "transparent", StringComparison.OrdinalIgnoreCase))
            return true;

        if (jsonMaterial != null)
        {
            // Prefer explicit per-channel alpha flags (from BlenRose JSON when present).
            if (jsonMaterial.ChannelAlphaFlags.TryGetValue(meshChannelName, out bool hasAlpha))
                return hasAlpha;
        }

        // By default, all non-transparent channels are treated as opaque unless
        // JSON explicitly marks them as alpha-using.
        return false;
    }

    private static byte[] ReadAllBytes(MemoryImage memoryImage)
    {
        using var stream = memoryImage.Open();
        using var ms = new MemoryStream();
        stream.CopyTo(ms);
        return ms.ToArray();
    }

    private static string ResolveImageName(Image image, MemoryImage content, string fallbackChannelName)
    {
        if (!string.IsNullOrWhiteSpace(image.Name))
            return image.Name!;

        if (!string.IsNullOrWhiteSpace(content.SourcePath))
            return Path.GetFileNameWithoutExtension(content.SourcePath);

        return fallbackChannelName;
    }
}

